spring.application.name=la-mia-pizzeria-crud

# Connessione al database
spring.datasource.url=jdbc:mysql://localhost:3306/lamiapizzeria-crud
spring.datasource.username=root
spring.datasource.password=root

# Hibernate crea/aggiorna le tabelle in automatico
spring.jpa.hibernate.ddl-auto=update

# Mostra query SQL nel terminale
spring.jpa.show-sql=true
